config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get "saisons/:season_years", to: "pages#season_show", as: "season_show"
  resources :schedules, only: [:show]

  get "power", to: "pages#power"
  scope '/power' do
    resources :seasons, only: [:index, :create, :show, :destroy] do
      member do
        get :stats_stabis
      end
    end
    resources :competitions, only: [:index, :create, :show, :destroy]
    resources :teams, only: [:index, :create, :show]
    resources :stadiums, only: [:new, :create, :index, :edit, :update]
    resources :editions, only: [:index, :create]
    resources :editions, only: [:show] do
      resources :contestants, only: [:index, :create]
      resources :schedules, only: [:index, :create] do
        post "results", to: "results#update_results"
      end
      post "games", to: "schedules#generate_games"
    end
    get "results(/:id)", to: "results#enter_results", as: "enter_results"
    resources :articles
    resources :user_roles, only: [:index, :create, :destroy]
  end

  # Path related to registering preferences in client browser cookies
  post 'update_preferences', to: 'preferences#update'
  post 'cookies_refusal_preferences', to: 'preferences#cookies_refusal'
end

app/models/edition.rb
class Edition < ApplicationRecord
  belongs_to :competition
  belongs_to :season
  has_many :contestants
  has_many :teams, through: :contestants
  has_many :schedules
  has_many :articles

  validates :competition_id, uniqueness: { scope: :season_id }

  def label_for_select
    "#{self.season.years}/#{self.competition.kind}/#{self.competition.name}"
  end
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController

  def index
    @editions = Edition.all.order(:season_id, :competition_id)
    @edition = Edition.new
  end

  def create
    @edition = Edition.new(edition_params)
    if @edition.save
      redirect_to editions_path
    end
  end

  def show
    @edition = Edition.find(params[:id])
  end

  private

  def edition_params
    params.require(:edition).permit(:season_id, :competition_id)
  end
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/views/editions/index.html.erb
<h1>Competition Editions</h1>
<%= simple_form_for @edition do |f| %>
  <%= f.association :season, value_method: :id, label_method: :years %>
  <%= f.association :competition, value_method: :id, label_method: :name %>
  <%= f.button :submit %>
<% end -%>


<ul>
  <% @editions.each do |edition| %>
    <li>
      <%= link_to "(#{edition.season.id})" + edition.season.years + "/ (#{edition.competition.id})" + edition.competition.name, edition_path(edition) %>
    </li>
  <% end %>
</ul>

app/views/editions/show.html.erb
<h1><%= @edition.season.years + " / " + @edition.competition.name %></h1>
<ul>
  <li><%= link_to "Contestants Teams", edition_contestants_path(@edition) %></li>
  <li><%= link_to "Calendar / results", edition_schedules_path(@edition) %></li>
  <li>Generate Calendar</li>
</ul>