config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get "saisons/:season_years", to: "pages#season_show", as: "season_show"
  resources :schedules, only: [:show]

  get "power", to: "pages#power"
  scope '/power' do
    resources :seasons, only: [:index, :create, :show, :destroy] do
      member do
        get :stats_stabis
      end
    end
    resources :competitions, only: [:index, :create, :show, :destroy]
    resources :teams, only: [:index, :create, :show]
    resources :stadiums, only: [:new, :create, :index, :edit, :update]
    resources :editions, only: [:index, :create]
    resources :editions, only: [:show] do
      resources :contestants, only: [:index, :create]
      resources :schedules, only: [:index, :create] do
        post "results", to: "results#update_results"
      end
      post "games", to: "schedules#generate_games"
    end
    get "results(/:id)", to: "results#enter_results", as: "enter_results"
    resources :articles
    resources :user_roles, only: [:index, :create, :destroy]
  end

  # Path related to registering preferences in client browser cookies
  post 'update_preferences', to: 'preferences#update'
  post 'cookies_refusal_preferences', to: 'preferences#cookies_refusal'
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  default_scope { order(day: :asc) }

  # attr_accessor :first_day
  belongs_to :edition
  has_many :games, dependent: :destroy

  # after_update :delay_all_season_schedules_day

  accepts_nested_attributes_for :games


  def next
    next_schedule = self.class.where("day > ?", self.class.find(id).day).first
    self.edition == next_schedule&.edition ? next_schedule : nil
  end

  def next_in_season
    next_schedule = self.class.where("day > ?", self.class.find(id).day).first
    self.season == next_schedule&.season ? next_schedule : nil
  end

  def previous
    previous_schedule = self.class.where("day < ?", self.class.find(id).day).last
    self.edition == previous_schedule&.edition ? previous_schedule : nil
  end

  def previous_in_season
    previous_schedule = self.class.where("day < ?", self.class.find(id).day).last
    self.season == previous_schedule&.season ? previous_schedule : nil
  end

  def season
    self.edition.season
  end

  def self.delay_season_calendar_from_given_schedule(schedule_start)
    return nil unless schedule_start.is_a? Schedule

    current_season = schedule_start.edition.season
    schedule_iterator = schedule_start
    # while next schedule exist AND is still on the same season
    # so I can continue iteration
    while schedule_iterator
      if schedule_iterator.next.present?
        if schedule_iterator.next.edition.season == current_season
          # take the next schedule day to the current schedule

          schedule_iterator.update(day: schedule_iterator.next.day)
          puts "[A] - #{schedule_iterator.designation}: #{schedule_iterator.day} --> #{schedule_iterator.next.day}"
        else
          # .next exist AND next season != current_season
          # Add 7 days to the last schedule of the season

          schedule_iterator.update(day: schedule_iterator.day + 7.days)
          puts "[B] - #{schedule_iterator.designation}: #{schedule_iterator.day} --> #{schedule_iterator.day + 7.days}"
        end
      else
        # It is the last schedule record
        # Add 7 days to the last schedule of the season

        schedule_iterator.update(day: schedule_iterator.day + 7.days)
        puts "[C] - #{schedule_iterator.designation}: #{schedule_iterator.day} --> #{schedule_iterator.day + 7.days}"
      end
      schedule_iterator = schedule_iterator.next
    end
  end

  private

  def delay_all_season_schedules_day
    current_season = self.edition.season
    schedule_iterator = self.next
    # while next schedule exist AND is still on the same season
    # so I can continue iteration
    if schedule_iterator.present?
      if schedule_iterator.next.present?
        if schedule_iterator.next.edition.season == current_season
          # take the next schedule day to the current schedule
          schedule_iterator.update(day: schedule_iterator.next.day)
        else
          # .next exist AND next season != current_season
          # Add 7 days to the last schedule of the season
          schedule_iterator.update(day: schedule_iterator.day + 7)
        end
      else
        # It is the last schedule record
        # Add 7 days to the last schedule of the season
        schedule_iterator.update(day: schedule_iterator.day + 7)
      end
    end
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  respond_to :html, :js

  def index
    @edition = Edition.find(params[:edition_id])
    @schedules = Schedule.where(edition: params[:edition_id])
    @schedule = Schedule.new
  end

  def show
    @schedule = Schedule.find(params[:id])
    respond_to do |format|
      format.js {render layout: false}
      format.html
    end
  end

  def create
    @edition = Edition.find(params[:edition_id])
    # Recieve first schedule date from the form
    @schedule = Schedule.new(schedule_params)

    # initialise round number
    i = 1

    current_date = (Time.now + Time.now.utc_offset).utc
    # if first day schedule (send through form) is in the futur
    if (@schedule.day > current_date)
      # then save 1st schedule
      @schedule.designation = "J" + sprintf("%02d",i)
      @schedule.edition = @edition
      if @schedule.save
        i += 1
        # then create next ones (date + 7 days) btw 2 schedules
        while i <= ((@edition.teams.count - 1 + (@edition.teams.count % 2)) * 2)
          # create new schedule 7 days later
          Schedule.create(
            edition: @edition,
            day: Schedule.all.last.day + 7,
            designation: "J" + sprintf("%02d",i))
          # increment round number
          i += 1
        end
        redirect_to edition_schedules_path(@edition)
      end
    end
  end

  def generate_games
    @edition = Edition.find(params[:edition_id])

    # Generate a RoundRobin for @edition.teams
    first_legs_games = RoundRobinTournament.schedule(@edition.teams.shuffle)

    schedule = @edition.schedules.order(:created_at).first
    first_legs_games.each do |day|
      day.each do |game|
        if game.compact.count == 2
          new_game = Game.create(schedule: schedule)
          Result.create(game: new_game, team: game.first)
          Result.create(game: new_game, team: game.last)
        end
      end
      schedule = schedule.next
    end
    second_legs_games = first_legs_games.shuffle
    second_legs_games.each do |day|
      day.each do |game|
        if game.compact.count == 2
          new_game = Game.create(schedule: schedule)
          Result.create(game: new_game, team: game.last)
          Result.create(game: new_game, team: game.first)
        end
      end
      schedule = schedule.next
    end

  end

  private

  def schedule_params
    params.require(:schedule).permit(:day)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_show.html.erb
<% is_cup = schedule.edition.competition.kind == "cup" %>
<div class="schedule-header">
  <%= link_to schedule.previous_in_season, remote: true do %>
    <%= fa_icon("chevron-circle-left", class: "change-schedule") %>
  <% end %>
  <div class="schedule-designation">
    <% if schedule.edition.competition.kind == "championship" %>
      <%= "Journée " + schedule.designation.split("J")[1] %>
    <% elsif schedule.edition.competition.kind == "cup" %>
      <%= "Cup " + schedule.designation %>
    <% else %>
      <%= "Amical " + schedule.designation %>
    <% end %>
    <div class="info">
      <%= schedule.day.strftime("%d/%m/%Y") %>
    </div>
  </div>
  <%= link_to schedule.next_in_season, remote: true do %>
    <%= fa_icon("chevron-circle-right", class: "change-schedule") %>
  <% end %>
</div>

<div class="modern-matches">
  <% schedule.games.sort_by(&:day).each do |game| %>
    <div class="match-container" data-controller="games">
      <!-- Div stade qui apparaitra -->
      <div data-games-target="stadium" class="stadium-overlay">
        <%= game.stadium&.name || '--' %>
      </div>

      <!-- Barre principale -->
      <div data-games-target="mainContent" class="match-bar">
        <div class="team team-left">
          <span class="team-name-full" data-games-target="team" data-team-id="<%= game.results.first.team.id %>"><%= game.results.first.team.team_names.last.name %></span>
          <span class="team-name-short"><%= game.results.first.team.team_names.last.name.first(5).upcase %></span>
          <%= fa_icon("flag", class: "forfeit-flag", title: "Forfait") if game.results.first.forfeit %>
        </div>

        <div data-games-target="score" class="score-section">
          <% if game.status == "delayed" %>
            <span class="status-text">Reporté</span>
          <% elsif game.status == "canceled" %>
            <span class="status-text">Annulé</span>
          <% elsif game.status == "played" %>
            <% draw = game.results.first.mark == game.results.last.mark %>
            <div class="score-display">
              <div class="score-number left">
                <% if draw && is_cup %><sub class="penalty">(<%= game.results.first.penalty_mark %>)</sub><% end %><%= game.results.first.mark %>
              </div>
              <div class="score-number right">
                <%= game.results.last.mark %><% if draw && is_cup %><sub class="penalty">(<%= game.results.last.penalty_mark %>)</sub><% end %>
              </div>
            </div>
          <% end %>
        </div>

        <div class="team team-right">
          <%= fa_icon("flag", class: "forfeit-flag", title: "Forfait") if game.results.last.forfeit %>
          <span class="team-name-full" data-games-target="team" data-team-id="<%= game.results.last.team.id %>"><%= game.results.last.team.team_names.last.name %></span>
          <span class="team-name-short"><%= game.results.last.team.team_names.last.name.first(4).upcase %></span>
        </div>

        <button data-games-target="button" data-action="click->games#toggle" class="stadium-btn">
          <%= fa_icon("angle-double-left") %>
        </button>
      </div>
    </div>
  <% end %>
</div>

app/views/schedules/index.html.erb
<h1>Calendar for <%= @edition.competition.name + "/" + @edition.season.years %></h1>
Total_Rounds : <%= @edition.total_rounds %> <br>
Total Teams : <strong><%= @edition.teams.count %></strong> <br>
<%= link_to "Add Contestant Teams", edition_contestants_path(@edition) %> <br>
OR
<%= simple_form_for [@edition, @schedule] do |f| %>
  <%= f.input :day, as: :date, html5: true, label: "Date de la 1ere journée" %>
  <%= f.button :submit, "Generate Championship Calendar" %>
<% end %>
<br>
<br>
<%= simple_form_for @edition, method: :post, url: edition_games_path do |f| %>
  <%= f.button :submit, "Generate Championship Games" %>
<% end %>


<% @edition.schedules.each do |schedule| %>
  <strong>
  <%= schedule.designation + ": " + schedule.day.strftime("%d/%m/%Y") %> <br>
  </strong>
  <% schedule.games.each do |game| %>
  <%= game.results.first.team.team_names.last.name + " VS " + game.results.last.team.team_names.last.name %> <br>
  <% end %>
  <br>

<% end %>

app/views/schedules/show.js.erb
console.log("Show schedule");
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)){
  // for mobile device iOS
  <% device = 'ios' %>
}else if(/Android|webOS|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){
  // for mobile device ANDROID
  <% device = 'android' %>
} else {
  // for not mobile
  <% device = 'desktop' %>
}
document.querySelector("#active-schedule").innerHTML =
  "<%= escape_javascript(render partial: 'schedules/show', locals: { schedule: @schedule, device: device } ) %>";


/* START - THIS IS FOR THE SELECT ACTIVE SCHEDULE */
// document.querySelector("#select-schedule > .active").classList.toggle("active");
// document.querySelector("[data-num='<%= @schedule.designation %>']").classList.toggle("active");
/* END - NO MORE USED, IT IS HIDDEN */

var copyToClipboard = (event) => {
  console.log("Action copy");
  console.log(event.target);
  let address = event.target.querySelector(".address-to-clipboard");
  if (!address) {
    address = event.target.parentElement.querySelector(".address-to-clipboard");
  }
  if (address) {
    console.log(address.value);
    address.select();
    document.execCommand("copy");
  }
}

var prepareActionsCopyToClipboard = () => {
  const links = document.querySelectorAll(".link-copy-to-clipboard");
  if (links) {
    links.forEach( link => {
      link.addEventListener("click", copyToClipboard);
    });
  }
}

if (document.readyState !== 'loading') {
  console.log("Loaded");
  /* START - THIS IS FOR THE SELECT SCHEDULE AUTO SCROLL */
  // const outerContent = document.querySelector("#select-schedule");
  // console.log(outerContent.offsetHeight);
  // console.log(outerContent.scrollHeight);

  // const activeElement = document.querySelector("#select-schedule > .active");
  // console.log(activeElement.offsetHeight);
  // console.log(activeElement.offsetTop);

  // outerContent.scrollTo(0,activeElement.offsetTop);
  /* END - NO MORE USED, IT IS HIDDEN */

  prepareActionsCopyToClipboard();
}
// else {
//   document.addEventListener('DOMContentLoaded', eventHandler);
// }

if (window.StimulusApplication) {
  requestAnimationFrame(() => {
    window.StimulusApplication.stop()
    window.StimulusApplication.start()
    
    // Vérification après reconnexion
    //const controllers = document.querySelectorAll('[data-controller="games"]')
    //console.log("Nombre de contrôleurs games trouvés:", controllers.length)
  });
}